### ISSUE TITLE
Source connector issue with TINYINT

### ISSUE THREAD

**Issue by sreekanthtdhar** [SAP/kafka-connect-sap#1]
When table is having TINYINT datatype the connector fails with the below error. Running the connector in query mode with casting to varchar is working. 

```
[2018-03-28 23:39:18,219] ERROR Task connect-hana-source-0 threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:141)
com.sap.kafka.client.hana.HANAJdbcException: execution of query select * from "DB"."HANA_SAMPLE_TABLE" failed
        at com.sap.kafka.client.hana.HANAJdbcClient.executeQuery(HANAJdbcClient.scala:355)
        at com.sap.kafka.connect.source.querier.TableQuerier.maybeStartQuery(TableQuerier.scala:44)
        at com.sap.kafka.connect.source.GenericSourceTask.poll(GenericSourceTask.scala:161)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:162)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:139)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:182)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:744)
Caused by: org.apache.kafka.connect.errors.DataException: Invalid Java object for schema type INT8: class java.lang.Integer
        at org.apache.kafka.connect.data.ConnectSchema.validateValue(ConnectSchema.java:233)
        at org.apache.kafka.connect.data.Struct.put(Struct.java:215)
        at org.apache.kafka.connect.data.Struct.put(Struct.java:204)
        at com.sap.kafka.client.hana.HANAJdbcClient$$anonfun$com$sap$kafka$client$hana$HANAJdbcClient$$fetchResultSet$1.apply(HANAJdbcClient.scala:393)
        at com.sap.kafka.client.hana.HANAJdbcClient$$anonfun$com$sap$kafka$client$hana$HANAJdbcClient$$fetchResultSet$1.apply(HANAJdbcClient.scala:390)
        at scala.collection.immutable.Range.foreach(Range.scala:160)
        at com.sap.kafka.client.hana.HANAJdbcClient.com$sap$kafka$client$hana$HANAJdbcClient$$fetchResultSet(HANAJdbcClient.scala:390)
        at com.sap.kafka.client.hana.HANAJdbcClient$$anonfun$35$$anonfun$36$$anonfun$37$$anonfun$39.apply(HANAJdbcClient.scala:364)
        at com.sap.kafka.client.hana.HANAJdbcClient$$anonfun$35$$anonfun$36$$anonfun$37$$anonfun$39.apply(HANAJdbcClient.scala:363)
        at com.sap.kafka.utils.WithCloseables$.apply(WithCloseables.scala:36)
        at com.sap.kafka.client.hana.HANAJdbcClient$$anonfun$35$$anonfun$36$$anonfun$37.apply(HANAJdbcClient.scala:363)
        at com.sap.kafka.client.hana.HANAJdbcClient$$anonfun$35$$anonfun$36$$anonfun$37.apply(HANAJdbcClient.scala:357)
        at com.sap.kafka.utils.WithCloseables$.apply(WithCloseables.scala:36)
        at com.sap.kafka.client.hana.HANAJdbcClient$$anonfun$35$$anonfun$36.apply(HANAJdbcClient.scala:357)
        at com.sap.kafka.client.hana.HANAJdbcClient$$anonfun$35$$anonfun$36.apply(HANAJdbcClient.scala:356)
        at com.sap.kafka.utils.WithCloseables$.apply(WithCloseables.scala:36)
        at com.sap.kafka.client.hana.HANAJdbcClient$$anonfun$35.apply(HANAJdbcClient.scala:356)
        at com.sap.kafka.client.hana.HANAJdbcClient$$anonfun$35.apply(HANAJdbcClient.scala:355)
        at com.sap.kafka.utils.ExecuteWithExceptions$.apply(ExecuteWithExceptions.s
```

**Comment by sbcd90** [comment]
Hi @sreekanthtdhar ,
this issue should be fixed now with [PR-2](https://github.com/SAP/kafka-connect-sap/pull/2).
Please pull the latest code & try the scenario again.

**Comment by sreekanthtdhar** [comment]
Hi @sbcd90 ,
Connector is working fine with TINYINT. Thanks for the fix. Closing the issue.
