### ISSUE TITLE
Build dependencies are missing

### ISSUE THREAD

**Issue by jorgechato** [SAP/kafka-connect-sap#24]
I modify the pom in order to create a fat-jar with all dependencies but still rise the `java.lang.ClassNotFoundException`

**POM**:

```xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

<modelVersion>4.0.0</modelVersion>
<groupId>com.sap</groupId>
<artifactId>kafka-connect-hana</artifactId>
<version>1.0-SNAPSHOT</version>

<properties>
	<scala.version>2.11.8</scala.version>
	<scala.binary.version>2.11</scala.binary.version>
	<kafka.version>0.11.0.3</kafka.version>
	<kafka.dev.version>0.10.2.0-SNAPSHOT</kafka.dev.version>
</properties>

<repositories>
	<repository>
		<id>confluent</id>
		<url>http://packages.confluent.io/maven/</url>
		<snapshots>
			<enabled>true</enabled>
		</snapshots>
	</repository>
	<repository>
		<id>central</id>
		<name>central</name>
		<url>http://central.maven.org/maven2/</url>
	</repository>
</repositories>

<dependencies>
	<!-- scala dependency -->
	<dependency>
		<groupId>org.scala-lang</groupId>
		<artifactId>scala-library</artifactId>
		<version>${scala.version}</version>
	</dependency>

	<!-- kafka dependency -->
	<!-- switch to ${kafka.version} for using a stable release -->
	<dependency>
		<groupId>org.apache.kafka</groupId>
		<artifactId>kafka_${scala.binary.version}</artifactId>
		<version>${kafka.version}</version>
	</dependency>
	<dependency>
		<groupId>org.apache.kafka</groupId>
		<artifactId>connect-api</artifactId>
		<version>${kafka.version}</version>
		<scope>compile</scope>
	</dependency>
	<dependency>
		<groupId>io.confluent</groupId>
		<artifactId>kafka-schema-registry-client</artifactId>
		<version>3.0.0</version>
		<exclusions>
			<exclusion>
				<groupId>org.codehaus.jackson</groupId>
				<artifactId>jackson-core-asl</artifactId>
			</exclusion>
			<exclusion>
				<groupId>org.codehaus.jackson</groupId>
				<artifactId>jackson-mapper-asl</artifactId>
			</exclusion>
		</exclusions>
	</dependency>

	<!-- misc dependencies -->
	<dependency>
		<groupId>com.google.guava</groupId>
		<artifactId>guava</artifactId>
		<version>19.0</version>
	</dependency>
	<dependency>
		<groupId>com.google.code.findbugs</groupId>
		<artifactId>jsr305</artifactId>
		<version>2.0.3</version>
	</dependency>
	<dependency>
		<groupId>com.fasterxml.jackson.module</groupId>
		<artifactId>jackson-module-scala_${scala.binary.version}</artifactId>
		<version>2.4.4</version>
	</dependency>

	<!-- test dependencies -->
	<dependency>
		<groupId>com.h2database</groupId>
		<artifactId>h2</artifactId>
		<version>1.4.192</version>
		<scope>test</scope>
	</dependency>
	<dependency>
		<groupId>org.mockito</groupId>
		<artifactId>mockito-all</artifactId>
		<version>1.10.19</version>
		<scope>test</scope>
	</dependency>
	<dependency>
		<groupId>org.scalatest</groupId>
		<artifactId>scalatest_${scala.binary.version}</artifactId>
		<version>2.2.2</version>
		<scope>test</scope>
	</dependency>
</dependencies>

<build>
	<sourceDirectory>src/main/scala</sourceDirectory>
	<testSourceDirectory>src/test/scala</testSourceDirectory>
	<testResources>
		<testResource>
			<directory>src/test/resources</directory>
			<filtering>true</filtering>
			<includes>
				<include>**/*.properties</include>
			</includes>
		</testResource>
		<testResource>
			<directory>src/test/resources</directory>
			<filtering>false</filtering>
			<excludes>
				<exclude>**/*.properties</exclude>
			</excludes>
		</testResource>
	</testResources>
	<plugins>
		<!-- maven scala plugin -->
		<plugin>
			<groupId>org.scala-tools</groupId>
			<artifactId>maven-scala-plugin</artifactId>
			<executions>
				<execution>
					<goals>
						<goal>compile</goal>
						<goal>testCompile</goal>
					</goals>
				</execution>
			</executions>
			<configuration>
				<scalaVersion>${scala.version}</scalaVersion>
				<args>
					<arg>-target:jvm-1.5</arg>
				</args>
			</configuration>
		</plugin>


		<plugin>
			<groupId>org.apache.maven.plugins</groupId>
			<artifactId>maven-assembly-plugin</artifactId>
			<version>3.1.1</version>

			<configuration>
				<descriptorRefs>
					<descriptorRef>jar-with-dependencies</descriptorRef>
				</descriptorRefs>
			</configuration>

			<executions>
				<execution>
					<id>make-assembly</id>
					<phase>package</phase>
					<goals>
						<goal>single</goal>
					</goals>
				</execution>
			</executions>

		</plugin>

		<!-- maven shade plugin to bundle the jdbc driver -->
		<!--plugin>
			<groupId>org.apache.maven.plugins</groupId>
			<artifactId>maven-shade-plugin</artifactId>
			<version>2.4.3</version>
			<executions>
			<execution>
			<phase>package</phase>
			<goals>
			<goal>shade</goal>
			</goals>
			<configuration>
			<artifactSet>
			<includes>
			<include>com.google.protobuf:protobuf-java</include>
			<include>com.sap.hl.jdbc:hl-jdbc</include>
			<include>com.ecwid.consul:consul-api</include>
			</includes>
			</artifactSet>
			</configuration>
			</execution>
			</executions>
		</plugin-->

		<!-- disable surefire -->
		<plugin>
			<groupId>org.apache.maven.plugins</groupId>
			<artifactId>maven-surefire-plugin</artifactId>
			<version>2.19.1</version>
			<configuration>
				<skipTests>true</skipTests>
			</configuration>
		</plugin>
		<!-- enable scalatest -->
		<plugin>
			<groupId>org.scalatest</groupId>
			<artifactId>scalatest-maven-plugin</artifactId>
			<version>1.0</version>
			<configuration>
				<reportsDirectory>${project.build.directory}/surefire-reports</reportsDirectory>
				<junitxml>.</junitxml>
				<filereports>TestSuite.txt</filereports>
			</configuration>
			<executions>
				<execution>
					<id>test</id>
					<goals>
						<goal>test</goal>
					</goals>
				</execution>
			</executions>
		</plugin>
	</plugins>
</build>
</project>

```

**LOG**:

```bash
[2020-01-27 15:42:54,360] ERROR WorkerSinkTask{id=HANASinkConnector-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted. (org.apache.kafka.connect.runtime.WorkerSinkTask)
java.lang.NoClassDefFoundError: com/fasterxml/jackson/module/scala/DefaultScalaModule$
	at com.sap.kafka.client.hana.HANAPartitionLoader$.<init>(HANAPartitionLoader.scala:8)
	at com.sap.kafka.client.hana.HANAPartitionLoader$.<clinit>(HANAPartitionLoader.scala)
	at com.sap.kafka.client.hana.HANAJdbcClient$$anonfun$9.apply$mcV$sp(HANAJdbcClient.scala:360)
	at com.sap.kafka.client.hana.HANAJdbcClient$$anonfun$9.apply(HANAJdbcClient.scala:358)
	at com.sap.kafka.client.hana.HANAJdbcClient$$anonfun$9.apply(HANAJdbcClient.scala:358)
	at com.sap.kafka.utils.ExecuteWithExceptions$.apply(ExecuteWithExceptions.scala:40)
	at com.sap.kafka.client.hana.HANAJdbcClient.loadData(HANAJdbcClient.scala:358)
	at com.sap.kafka.connect.sink.hana.HANASinkRecordsCollector.flush(HANASinkRecordsCollector.scala:159)
	at com.sap.kafka.connect.sink.hana.HANAWriter$$anonfun$flush$2.apply(HANAWriter.scala:74)
	at com.sap.kafka.connect.sink.hana.HANAWriter$$anonfun$flush$2.apply(HANAWriter.scala:73)
	at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:733)
	at scala.collection.immutable.Map$Map1.foreach(Map.scala:116)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:732)
	at com.sap.kafka.connect.sink.hana.HANAWriter.flush(HANAWriter.scala:73)
	at com.sap.kafka.connect.sink.hana.HANAWriter.write(HANAWriter.scala:67)
	at com.sap.kafka.connect.sink.GenericSinkTask.put(GenericSinkTask.scala:36)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:524)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:302)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:205)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:173)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.module.scala.DefaultScalaModule$
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at org.apache.kafka.connect.runtime.isolation.PluginClassLoader.loadClass(PluginClassLoader.java:104)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 27 more
[2020-01-27 15:42:54,362] ERROR WorkerSinkTask{id=HANASinkConnector-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask)
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:546)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:302)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:205)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:173)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: com/fasterxml/jackson/module/scala/DefaultScalaModule$
	at com.sap.kafka.client.hana.HANAPartitionLoader$.<init>(HANAPartitionLoader.scala:8)
	at com.sap.kafka.client.hana.HANAPartitionLoader$.<clinit>(HANAPartitionLoader.scala)
	at com.sap.kafka.client.hana.HANAJdbcClient$$anonfun$9.apply$mcV$sp(HANAJdbcClient.scala:360)
	at com.sap.kafka.client.hana.HANAJdbcClient$$anonfun$9.apply(HANAJdbcClient.scala:358)
	at com.sap.kafka.client.hana.HANAJdbcClient$$anonfun$9.apply(HANAJdbcClient.scala:358)
	at com.sap.kafka.utils.ExecuteWithExceptions$.apply(ExecuteWithExceptions.scala:40)
	at com.sap.kafka.client.hana.HANAJdbcClient.loadData(HANAJdbcClient.scala:358)
	at com.sap.kafka.connect.sink.hana.HANASinkRecordsCollector.flush(HANASinkRecordsCollector.scala:159)
	at com.sap.kafka.connect.sink.hana.HANAWriter$$anonfun$flush$2.apply(HANAWriter.scala:74)
	at com.sap.kafka.connect.sink.hana.HANAWriter$$anonfun$flush$2.apply(HANAWriter.scala:73)
	at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:733)
	at scala.collection.immutable.Map$Map1.foreach(Map.scala:116)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:732)
	at com.sap.kafka.connect.sink.hana.HANAWriter.flush(HANAWriter.scala:73)
	at com.sap.kafka.connect.sink.hana.HANAWriter.write(HANAWriter.scala:67)
	at com.sap.kafka.connect.sink.GenericSinkTask.put(GenericSinkTask.scala:36)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:524)
	... 10 more
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.module.scala.DefaultScalaModule$
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at org.apache.kafka.connect.runtime.isolation.PluginClassLoader.loadClass(PluginClassLoader.java:104)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 27 more
```

**Comment by pgtips55** [comment]
I have the exact same issue. Did you get this resolved?
Thanks

**Comment by jorgechato** [comment]
I decide to use the JDBC connector, straight forward configuration without headaches.
Using this connector does not make sense.

**Comment by ashwini-fivetran** [comment]
> I decide to use the JDBC connector, straight forward configuration without headaches.

Can you elaborate more. I am working on a project to extract data out of SAP HANA S/4.
