### ISSUE TITLE
Incremental mode does not work with a different date format.

### ISSUE THREAD

**Issue by xrokrx** [SAP/kafka-connect-sap#41]
I have been trying to load data from SAP HANA to HDFS and I am using "AEDAT" as the incrementing column.
The date format "AEDAT" has is "YYYYMMDD", but the Kafka connector gives out the following error:

```
[2020-10-05 16:37:13,587] ERROR WorkerSourceTask{id=incremental-source-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:186)
java.lang.IllegalArgumentException: The Incrementing column is not found in the table or is not of correct type
        at com.sap.kafka.connect.source.querier.IncrColTableQuerier.getIncrementingColumn(IncrColTableQuerier.scala:106)
        at com.sap.kafka.connect.source.querier.IncrColTableQuerier.<init>(IncrColTableQuerier.scala:21)
        at com.sap.kafka.connect.source.GenericSourceTask.$anonfun$start$8(GenericSourceTask.scala:121)
        at com.sap.kafka.connect.source.GenericSourceTask.$anonfun$start$8$adapted(GenericSourceTask.scala:99)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at com.sap.kafka.connect.source.GenericSourceTask.start(GenericSourceTask.scala:99)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:215)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:184)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:234)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

hana-source.properties
```
name=incremental-source
connector.class=com.sap.kafka.connect.source.hana.HANASourceConnector
tasks.max=1
topics=saptohdfs
connection.url=jdbc:sap://xx.xx.xx.xx:30041/
connection.user=user
connection.password=pass
saptohdfs.table.name="SAPHANADB"."EKPO"
mode=incrementing
saptohdfs.incrementing.column.name="AEDAT"

```

hdfs-sink.properties
```
name=hdfs-sink
connector.class=io.confluent.connect.hdfs.HdfsSinkConnector
hdfs.url=hdfs://ip-10-1-1-131.ap-south-1.compute.internal:8020/warehouse/tablespace/external/hive
tasks.max=1
topics=saptohdfs
flush.size=3
hive.integration=true
hive.metastore.uris=thrift://ip-10-1-1-131.ap-south-1.compute.internal:9083
schema.compatibility=BACKWARD
format.class=io.confluent.connect.hdfs.avro.AvroFormat
#value.converter=io.confluent.connect.avro.AvroConverter

```

**Comment by elakito** [comment]
ABAP AEDAT type is actually not a valid DATE type but represented as type NVARCHAR(8) in HANA.
The incremental mode only works with SQL numeric or date/time/timestamp types.

**Comment by xrokrx** [comment]
@elakito So, how can someone make it work in incremental mode? I am new to Kafka Connect. Please help me out here.

**Comment by elakito** [comment]
@xrokrx We could support other _comparable_ types such as NVARCHAR. I think this incremental loading part needs other changes as well. But first, I'll add this additional type handling to the current implementation.

**Comment by xrokrx** [comment]
It still gives out this error in incremental mode.

![image](https://user-images.githubusercontent.com/31558145/98902486-d7175380-24db-11eb-8b8d-965c244ec6ba.png)

**Comment by elakito** [comment]
@xrokrx did you use the build from the PR branch? We haven't merged the change to master. The fix is still only in the PR branch. If yes, we need to see the table column definition of your table to see if that column type is covered by the types added in this fix.

**Comment by elakito** [comment]
@xrokrx It looks like you are using the master branch because the error at line 106 or `IncrColTableQuerier.scala` shown in your terminal indicates the code in the master branch. In the fixed code, the same error would be raised at line 101.
https://github.com/elakito/kafka-connect-sap/blob/ay-incr/src/main/scala/com/sap/kafka/connect/source/querier/IncrColTableQuerier.scala#L101

**Comment by elakito** [comment]
@xrokrx It is merged in master.

**Comment by xrokrx** [comment]
@elakito Hi, Sorry for the late response. I tested it. It is still giving out the same error.

**Comment by elakito** [comment]
@xrokrx Could you paste the error stack trace? Do you see the same error at `IncrColTableQuerier.scala (106)` as before? As I mentioned earlier, if that is the case, you have somehow the old code. In the current code, this error would come from line 100.
https://github.com/SAP/kafka-connect-sap/blob/master/src/main/scala/com/sap/kafka/connect/source/querier/IncrColTableQuerier.scala#L100

And if that is where the error comes from, could you inspect the type of this column in HANA table? Thanks.

**Comment by xrokrx** [comment]
@elakito Hi, Here is the error stack trace.

```
[2020-11-25 14:17:16,846] INFO WorkerSourceTask{id=incremental-source-0} flushing 0 outstanding messages for offset commit (org.apache.kafka.connect.runtime.WorkerSourceTask:443)
[2020-11-25 14:17:16,847] ERROR WorkerSourceTask{id=incremental-source-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:186)
java.lang.IllegalArgumentException: The Incrementing column is not found in the table or is not of supported type
        at com.sap.kafka.connect.source.querier.IncrColTableQuerier.getIncrementingColumn(IncrColTableQuerier.scala:100)
        at com.sap.kafka.connect.source.querier.IncrColTableQuerier.<init>(IncrColTableQuerier.scala:21)
        at com.sap.kafka.connect.source.GenericSourceTask.$anonfun$start$8(GenericSourceTask.scala:121)
        at com.sap.kafka.connect.source.GenericSourceTask.$anonfun$start$8$adapted(GenericSourceTask.scala:99)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at com.sap.kafka.connect.source.GenericSourceTask.start(GenericSourceTask.scala:99)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:215)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:184)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:234)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[2020-11-25 14:17:16,848] ERROR WorkerSourceTask{id=incremental-source-0} Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:187)

```

**Comment by xrokrx** [comment]
@elakito Hi, Any update?

**Comment by elakito** [comment]
@xrokrx I am puzzled with this situation. Could you look at the column type of this table? I was told AEDAT is normally represented as NVARCHAR in HANA and if that is the case, it should have been handled with the current version. Unfortunately, the current code doesn't write the type name when this situation happens. So, I just added this error text to the master branch code. https://github.com/SAP/kafka-connect-sap/commit/35d0e66dad84d91f557a44bb3ff716dbe044a920

If you cannot inspect the column type of your HANA table using Hana Tool, you could try the updated code to find it out. Thanks.

**Comment by elakito** [comment]
The current code should log the column name and the type when the assigned type is unexpected/unhandled. As mentioned, if you can look at your table and tell us its column type seen in the HANA table. I only know AEDAT being represented as NVARCHAR in HANA.
