### ISSUE TITLE
HANAConfigMissingException:  A comma-separated list of topics is required to run

### ISSUE THREAD

**Issue by vilterpanitz** [SAP/kafka-connect-sap#5]
Hi All,

I'm currently facing a problem trying to get Kafka-Connect-SAP connector working properly.

I have done all the required configurations, including the JDBC driver on the same connector's directory.

This are my properties config:

```properties
name=kafka-connect-source
connector.class=com.sap.kafka.connect.source.hana.HANASourceConnector
tasks.max=1
topics=kafka_source_1,kafka_source_2
connection.url=jdbc:sap://hana/
connection.user=SYSTEM
connection.password=HXEHana1
kafka_source_1.table.name="SYSTEM"."KAFKA_SOURCES"
```

I have configure a docker image for Hana service, which is responding successfully from my Kafka containers.

``` bash
$ ping hana
PING hana (172.21.0.2): 56 data bytes
64 bytes from 172.21.0.2: seq=0 ttl=64 time=0.095 ms
64 bytes from 172.21.0.2: seq=1 ttl=64 time=0.142 ms
```
This is the current stacktrace.

```
com.sap.kafka.client.hana.HANAConfigMissingException: Mandatory parameter missing: A comma-separated list of topics is required to run the HANA-Kafka connectors
	at com.sap.kafka.connect.config.BaseParameters$class.getConfig(BaseParameters.scala:33)
	at com.sap.kafka.connect.config.hana.HANAParameters$.getConfig(HANAParameters.scala:13)
	at com.sap.kafka.connect.source.GenericSourceTask$$anonfun$1.apply$mcV$sp(GenericSourceTask.scala:35)
	at com.sap.kafka.connect.source.GenericSourceTask$$anonfun$1.apply(GenericSourceTask.scala:34)
	at com.sap.kafka.connect.source.GenericSourceTask$$anonfun$1.apply(GenericSourceTask.scala:34)
	at com.sap.kafka.utils.ExecuteWithExceptions$.apply(ExecuteWithExceptions.scala:40)
	at com.sap.kafka.connect.source.GenericSourceTask.start(GenericSourceTask.scala:34)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:157)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

It says that *_comma-separated list of topics is required to run the HANA-Kafka connectors_*, but they were specified on the properties.

Can you help me to figure this out?

**Comment by vilterpanitz** [comment]
Solved after rerun mvn commands
