### ISSUE TITLE
WorkerSinkTask threw an uncaught and unrecoverable exception - java.lang.NoClassDefFoundError: com/google/common/base/Function

### ISSUE THREAD

**Issue by twonly** [SAP/kafka-connect-sap#63]
Hi, 
I am running kafka_2.13.0-2.7.0 with kafka-connect-sap connector (2.13) which was built in windows with JRE 1.8.0_271, though my Linux Server (SLES 12.5) is with JRE 1.8.0_222.

When running example 2, the source looks normal and I could get the messages from kafka-console-consumer.sh. 
However, the sink failed with error WorkerSinkTask{id=test_topic_3_sink-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:187)
	java.lang.NoClassDefFoundError: com/google/common/base/Function

Not sure if the JRE version and OS difference where I built the connector JAR would cause this. (I am trying the build again in Linux with latest JRE 1.8.0_271. 
**Anyone can help on this would be highly appreciated.** 

Full error log from the connect command's output
[2021-01-17 11:10:12,301] ERROR WorkerSinkTask{id=test_topic_3_sink-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:187)
	java.lang.NoClassDefFoundError: com/google/common/base/Function
	        at com.sap.kafka.connect.sink.hana.HANASinkTask.initWriter(HANASinkTask.scala:27)
	        at com.sap.kafka.connect.sink.hana.HANASinkTask.start(HANASinkTask.scala:22)
	        at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:308)
	        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:196)
	        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:185)
	        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:234)
	        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	        at java.lang.Thread.run(Thread.java:748)
	Caused by: java.lang.ClassNotFoundException: com.google.common.base.Function
	        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	        at org.apache.kafka.connect.runtime.isolation.PluginClassLoader.loadClass(PluginClassLoader.java:104)
	        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	        ... 11 more
			[2021-01-17 11:10:12,303] INFO Stopping task (com.sap.kafka.connect.sink.hana.HANASinkTask:62)
	[2021-01-17 11:10:12,303] WARN Could not stop task (org.apache.kafka.connect.runtime.WorkerSinkTask:171)
	java.lang.NullPointerException
	        at com.sap.kafka.connect.sink.GenericSinkTask.stop(GenericSinkTask.scala:63)
	        at org.apache.kafka.connect.runtime.WorkerSinkTask.close(WorkerSinkTask.java:169)
	        at org.apache.kafka.connect.runtime.WorkerTask.doClose(WorkerTask.java:164)
	        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:190)
	        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:234)
	        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	        at java.lang.Thread.run(Thread.java:748)
	[2021-01-17 11:10:12,303] INFO Metrics scheduler closed (org.apache.kafka.common.metrics.Metrics:668)
	[2021-01-17 11:10:12,303] INFO Closing reporter org.apache.kafka.common.metrics.JmxReporter (org.apache.kafka.common.metrics.Metrics:672)
	[2021-01-17 11:10:12,304] INFO Metrics reporters closed (org.apache.kafka.common.metrics.Metrics:678)
	[2021-01-17 11:10:12,306] INFO App info kafka.consumer for connector-consumer-test_topic_3_sink-0 unregistered (org.apache.kafka.common.utils.AppInfoParser:83)

**Comment by twonly** [comment]
It looks like the guava is missing not not included somehow. May anyone suggest how to proceed?

**Comment by twonly** [comment]
After manually downloading the guava jar files from (https://jar-download.com/?search_box=guava) , and placing them under libs and plugins/*connect*/, both source and sink work normally now. 
Still, not sure why these jar files were not automatically downloaded and included via maven build. (Because I used a private maven repo?)

**Comment by preetilht** [comment]
I am getting the same issue when running sink, [https://github.com/SAP/kafka-connect-sap/issues/109](url) , I have manually downloaded the guava jar files and copied it to my mvn libs. Getting the same issue again, am I missing something? @twonly can you please help.
