### ISSUE TITLE
java.lang.ClassNotFoundException: com.sap.db.jdbc.Driver

### ISSUE THREAD

**Issue by Thomas-Dangleterre** [SAP/kafka-connect-sap#96]
Hello,

I try to run a source connector on  Kafka Connect, here is my docker image 

```
FROM confluentinc/cp-kafka-connect:6.2.0
RUN confluent-hub install --no-prompt splunk/kafka-connect-splunk:2.0.2
RUN confluent-hub install --no-prompt confluentinc/kafka-connect-s3:10.0.1

COPY ./target/ /usr/share/java/
COPY kafka-connector-hana_2.13-0.9.1.jar /usr/share/java/kafka-connector-hana_2.13-0.9.1.jar
```
> target directory  contains only ngdbc-2.9.16.jar before build

i'm getting a ClassNotFoundException when creating a source connector :
```
ERROR WorkerSourceTask{id=stockmvt-hana-source-connect-5-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask)
java.lang.ClassNotFoundException: com.sap.db.jdbc.Driver
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at org.apache.kafka.connect.runtime.isolation.PluginClassLoader.loadClass(PluginClassLoader.java:104)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at com.sap.kafka.client.hana.HANAJdbcClient.$anonfun$getConnection$1(HANAJdbcClient.scala:75)
	at com.sap.kafka.utils.ExecuteWithExceptions$.apply(ExecuteWithExceptions.scala:40)
	at com.sap.kafka.client.hana.HANAJdbcClient.getConnection(HANAJdbcClient.scala:71)
	at com.sap.kafka.connect.source.hana.HANASourceTask.getTables(HANASourceTask.scala:29)
	at com.sap.kafka.connect.source.GenericSourceTask.start(GenericSourceTask.scala:65)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:224)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:182)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:231)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

It seems like class Driver is not accessible but logs indicate us that the jar is correctly loaded  

```
[2021-09-17 12:23:44,772] INFO Loading plugin from: /usr/share/java/ngdbc-2.9.16.jar (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader)
[2021-09-17 12:23:44,887] INFO Registered loader: PluginClassLoader{pluginLocation=file:/usr/share/java/ngdbc-2.9.16.jar} (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader)
```

Could you tell me if there is a way to run Hana connector on Kafka Connect instead of Debezium ?

**Comment by elakito** [comment]
@Thomas-Dangleterre You are missing the JDBC provider library in your /target folder.  In the examples folder, you can find several docker based examples (e.g., persions1ds, etc), take one of them and follow its README that describe how to build the respective docker image or to fill the target folder with the required jars.

**Comment by Thomas-Dangleterre** [comment]
Yes, sorry for the late answer. 

Thank you
